[package]
name = "range-set"
version = "0.1.0"
edition = "2018"

[[bench]]
name = "comparison"
harness = false

[dependencies]
num-traits = "0.2.14"

[dev-dependencies]
criterion = "0.3.5"
rand = "0.8.4"
ranged_set = "0.4.1"
test-case = "1.2.0"
